# Generated by Django 5.0 on 2023-12-30 05:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("App_Video", "0001_initial"),
    ]

    operations = [migrations.DeleteModel('Video')]
