# Generated by Django 5.0 on 2023-12-30 11:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("App_Video", "0005_comment"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="blog",
            new_name="video",
        ),
    ]
